In [1]:
import pandas as pd

In [10]:
data = pd.read_excel("bird.xlsx", sheet_name="bird-species")

In [11]:
data["jenis_burung"].unique()
df_jenis = pd.DataFrame(data["jenis_burung"].unique(), columns=["jenis_burung"])

In [14]:
df_jenis = pd.DataFrame(data["jenis_burung"].unique(), columns=["jenis_burung"])
map_nama = data.set_index("jenis_burung")["nama_ilmiah"].to_dict()
df_jenis["nama_ilmiah"] = df_jenis["jenis_burung"].map(map_nama)
df_jenis

               jenis_burung                 nama_ilmiah
0              Blekok Sawah            Ardeola speciosa
1             Bondol Peking         Lonchura punctulata
2                Cangak Abu               Ardea cinerea
3              Cangak Merah              Ardea purpurea
4              Kokokan Laut          Butorides striatus
5              Kuntul Kecil            Egretta garzetta
6        Layang-Layang Batu            Hirundo javanica
7              Walet Linchi           Collocalia linchi
8           Dara Laut Biasa              Sterna hirundo
9             Kedidi Golgol         Calidris ferruginea
10             Kuntul Perak          Egretta intermedia
11         Pecuk Padi Kecil            Microcarbo niger
12                 Perkutut            Geopelia striata
13            Burung Gereja             Passer montanus
14         Pecuk Padi Hitam  Phalacrocorax sulcirostris
15               Bubut Jawa        Centropus nigrorufus
16                 Kutilang       Pycnonotus aurigaster
17          Dara Laut Kumis         Chlidonias hybridus
18             Cerek Melayu          Charadrius peronii
19            Perkutut Jawa            Geopelia striata
20               Kerak Ungu        Acridotheres tristis
21            Trinil Pantai           Tringa hypoleucos
22           Cucak Kutilang       Pycnonotus aurigaster
23         Kirik-Kirik Laut          Merops philippinus
24               Walet Sapi        Collocalia esculenta
25              Bondol Haji               Lonchura maja
26  Dara Laut Tengkuk Hitam            Sterna sumatrana
27      Kapasan Sayap Putih              Lalage sueurii
28               Kareo Padi      Amaurornis phoenicurus
29            Dara Domestik     Columba livia domestica
30               Dara Biasa               Columba livia
31               Dara Kumis          Chlidonias hybrida
32              Apung Tanah      Anthus novaeseelandiae
33                  Kapasan                      Lalage
34        Layang-Layang Gua             Hirundo daurica
35             Remetuk Laut          Gerygone sulphurea
36                 Walet Sp               Collocalia sp
37               Cerek Jawa        Charadrius javanicus
38            Bentet Kelabu               Lanius schach
39         Layang-Layang Sp             Hirundo rustica
40              Bondol Jawa    Lonchura leucogastroides
41              Bondol Ikan             Haliastur indus
42             Dederuk Jawa     Streptopelia bitorquata
43          Dara Laut Kecil            Sterna albifrons
44                  Dederuk                Streptopelia
45               Kekep Babi        Artamus leucorynchus
46            Kuntul Kerbau               Bubulcus ibis
47   Dara Laut Tenguk Hitam            Sterna sumatrana
48             Kuntul Besar                    Ardeidae
49                  Tekukur        Spilopelia chinensis
50               Kerak Jawa      Acridotheres javanicus
51              Mandar Padi                 Gallirallus

In [15]:
df_jenis.to_excel("jenis_burung.xlsx", index=False)
df_jenis

               jenis_burung                 nama_ilmiah
0              Blekok Sawah            Ardeola speciosa
1             Bondol Peking         Lonchura punctulata
2                Cangak Abu               Ardea cinerea
3              Cangak Merah              Ardea purpurea
4              Kokokan Laut          Butorides striatus
5              Kuntul Kecil            Egretta garzetta
6        Layang-Layang Batu            Hirundo javanica
7              Walet Linchi           Collocalia linchi
8           Dara Laut Biasa              Sterna hirundo
9             Kedidi Golgol         Calidris ferruginea
10             Kuntul Perak          Egretta intermedia
11         Pecuk Padi Kecil            Microcarbo niger
12                 Perkutut            Geopelia striata
13            Burung Gereja             Passer montanus
14         Pecuk Padi Hitam  Phalacrocorax sulcirostris
15               Bubut Jawa        Centropus nigrorufus
16                 Kutilang       Pycnonotus aurigaster
17          Dara Laut Kumis         Chlidonias hybridus
18             Cerek Melayu          Charadrius peronii
19            Perkutut Jawa            Geopelia striata
20               Kerak Ungu        Acridotheres tristis
21            Trinil Pantai           Tringa hypoleucos
22           Cucak Kutilang       Pycnonotus aurigaster
23         Kirik-Kirik Laut          Merops philippinus
24               Walet Sapi        Collocalia esculenta
25              Bondol Haji               Lonchura maja
26  Dara Laut Tengkuk Hitam            Sterna sumatrana
27      Kapasan Sayap Putih              Lalage sueurii
28               Kareo Padi      Amaurornis phoenicurus
29            Dara Domestik     Columba livia domestica
30               Dara Biasa               Columba livia
31               Dara Kumis          Chlidonias hybrida
32              Apung Tanah      Anthus novaeseelandiae
33                  Kapasan                      Lalage
34        Layang-Layang Gua             Hirundo daurica
35             Remetuk Laut          Gerygone sulphurea
36                 Walet Sp               Collocalia sp
37               Cerek Jawa        Charadrius javanicus
38            Bentet Kelabu               Lanius schach
39         Layang-Layang Sp             Hirundo rustica
40              Bondol Jawa    Lonchura leucogastroides
41              Bondol Ikan             Haliastur indus
42             Dederuk Jawa     Streptopelia bitorquata
43          Dara Laut Kecil            Sterna albifrons
44                  Dederuk                Streptopelia
45               Kekep Babi        Artamus leucorynchus
46            Kuntul Kerbau               Bubulcus ibis
47   Dara Laut Tenguk Hitam            Sterna sumatrana
48             Kuntul Besar                    Ardeidae
49                  Tekukur        Spilopelia chinensis
50               Kerak Jawa      Acridotheres javanicus
51              Mandar Padi                 Gallirallus